# Airflow Dockerfile
FROM apache/airflow:2.8.1-python3.10

USER root

RUN apt-get update && \
    apt-get clean

USER airflow

RUN pip install --upgrade pip

COPY requirements.txt /requirements.txt

RUN pip install --no-cache-dir -r /requirements.txt